pipeline:
  validate:
    image: quay.io/ukhomeofficedigital/terraform-toolset:v0.2.5
    commands:
    - /acp/scripts/tf-validate.sh -d terraform --no-docs
    when:
      event: [pull_request, push]
