---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: validate
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/terraform-toolset:v0.13.6
  commands:
  - /acp/scripts/tf-validate.sh --no-docs
  - /acp/scripts/tf-validate.sh -d gateway --no-docs
  when:
    event:
    - pull_request
    - push

...
